function [fitresult, gof] = createFit(BM, Times)
%CREATEFIT(BM,TIMES)
%  Create a fit.
%
%  Data for 'data 290 K fit' fit:
%      X Input: BM from data290
%      Y Output: Times from data290
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 19-Aug-2024 23:33:51


%% Fit: 'data 290 K fit'.
[xData, yData] = prepareCurveData( BM, Times );

% Set up fittype and options.
ft = fittype( 'exp1' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [211.41414199564 -105.054072402325];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'data fit at selected temperature' );
h = plot( fitresult, xData, yData );
legend( h, 'Times vs. BM', 'data fit at selected temp', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'BM', 'Interpreter', 'none' );
ylabel( 'Times', 'Interpreter', 'none' );
grid on


