function [fitresult, gof] = createSurfaceFit(BM, TemperatureK, Times)
%CREATEFIT1(BM,TEMPERATUREK,TIMES)
%  Create a fit.
%
%  Data for 'surface fit rxn kinetics' fit:
%      X Input: BM from kineticdata
%      Y Input: TemperatureK from kineticdata
%      Z Output: Times from kineticdata
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 19-Aug-2024 23:57:12


%% Fit: 'surface fit rxn kinetics'.
[xData, yData, zData] = prepareSurfaceData( BM, TemperatureK, Times );

% Set up fittype and options.
ft = fittype( 'a*exp(-b/y)*(x^c)', 'independent', {'x', 'y'}, 'dependent', 'z' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.445586200710899 0.646313010111265 0.709364830858073];

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, opts );

% Plot fit with data.
figure( 'Name', 'surface fit rxn kinetics' );
h = plot( fitresult, [xData, yData], zData );
legend( h, 'surface fit rxn kinetics', 'Times vs. BM, TemperatureK', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'BM', 'Interpreter', 'none' );
ylabel( 'TemperatureK', 'Interpreter', 'none' );
zlabel( 'Times', 'Interpreter', 'none' );
grid on


