function rxn_data = importfile(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  RXN_DATA = IMPORTFILE(FILE) reads data from the first worksheet in
%  the Microsoft Excel spreadsheet file named FILE.  Returns the data as
%  a table.
%
%  RXN_DATA = IMPORTFILE(FILE, SHEET) reads from the specified worksheet.
%
%  RXN_DATA = IMPORTFILE(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  rxn_data = importfile("C:\Users\garellan\OneDrive - MathWorks\Desktop\Demos\0000 - Gaby's repos\Seminario_IngQuimica\Data Analysis\rxn_data.xlsx", "Data", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 09-May-2025 10:38:25

%% Input handling

% If no sheet is specified, read from Data
if nargin == 1 || isempty(sheetName)
    sheetName = "Data";
end

% If row start and end points are not specified, define defaults
lastRowOfDataIdx = 0;
if nargin <= 2
    dataLines = [2, Inf];
    lastRowOfDataIdx = 1;
elseif dataLines(end,2) >= Inf
    lastRowOfDataIdx = size(dataLines, 1);
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 4);

% Specify sheet and range
opts.Sheet = sheetName;
if lastRowOfDataIdx == 1
    opts.DataRange = "A" + dataLines(1, 1);
else
    opts.DataRange = "A" + dataLines(1, 1) + ":D" + dataLines(1, 2);
end

% Specify column names and types
opts.VariableNames = ["A_M", "B_M", "Temperature_K", "Time_s"];
opts.VariableTypes = ["double", "double", "double", "double"];

% Import the data
rxn_data = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    if idx == lastRowOfDataIdx
        opts.DataRange = "A" + dataLines(idx, 1);
    else
        opts.DataRange = "A" + dataLines(idx, 1) + ":D" + dataLines(idx, 2);
    end
    tb = readtable(workbookFile, opts, "UseExcel", false);
    rxn_data = [rxn_data; tb]; %#ok<AGROW>
end

end